### ISSUE TITLE
Woocommerce - Logs view

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-woocommerce#131]
Currently we do not paint logs in this window. Investigate if there are ways to paint it or if we deprecate this window.

![image.png](https://images.zenhubusercontent.com/62cc16b840afcb2bb6a9b5b2/9b3e460c-6e34-42f2-a210-c98d9f23e0d0)

The current url to logs is public and it must be private. Review logs and just keep useful logs.

blocked by https://github.com/doofinder/doofinder-wordpress/issues/43

**Comment by eduardogomez97** [comment]
After investigating it I have been able to verify that we can create the Logs folder with specific permissions so that no external user can read it. It would be adding this parameter:
![image.png](https://images.zenhubusercontent.com/62cc16b840afcb2bb6a9b5b2/68167f1f-a607-4029-a64f-d6205f59d251)

Also on the subject of the actual logs we do not show anything because we use a class called TransientLogs, this is used in very specific cases such as internal search(for example is used in those who have the floating, without embedded) or shutdown. 

You would have to create a new log page based on the URL, indicating in it the type of logs. Then print on the screen the data of the file we want to see. We would have to print the last part of the file because some of them are too long.

**Comment by vferrero** [comment]
This is the restructuring of log file names that is going to be done:

- **store_create_index_status.log**: Log of all indexing completed. Here it is written after each callback index-status
- **reset-credential-api.log**: Every time the credentials are reset it is written here
- **store_create_api.log**: In each store creation the doomanager payload of the create-store request is logged
- **update-on-save-api.log**: Indexing update log via update_products
- **update-on-save-add-item.log**: Autosave log of products/posts/pages. Log is added when we save a product/post/page
- **log.txt**: Default log

On the other hand, we have eliminated sensitive information from the logs, such as API users and passwords since wp-content (log location) is accessible from the outside.

**Comment by vferrero** [comment]
Regarding the new log access/download functionality. We have 2 possible options:

**Option 1**: New "Log" tab where the client can download all the plugin logs in a zip.
**Option 2**: List of linkable log files so that the client can view each log file separately.

Personally, I see option 1 as more practical because this new functionality means that the client can download all the logs at once and send them to us so that we can investigate what has happened. I attach a screenshot of the tool:

![Image](https://github.com/doofinder/doofinder-woocommerce/assets/5503117/92873f73-c3c0-4444-b923-0bbd6db82d4c)

@CristobalDolz what do you think about this idea?

**Comment by vferrero** [comment]
Finally, this functionality will not be implemented, currently the client does not need to access the plugin logs and if we need it, we can access the logs publicly through URL.

The only thing we are going to do is clean and normalize the logs. Firstly, the names of the logs are going to be changed and secondly we are going to add a function in the update manager that will archive the old logs so that they are not mixed with the new log files.
