### ISSUE TITLE
[Est:8] [Wordpress] Make plugin compatible with woocommerce market

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-woocommerce#304]
https://witty-pelican-a6c.notion.site/Df-en-el-marketplace-de-Woocommerce-0df3025278f44b79a9d42ce74707cc88?pvs=4

**Comment by davidmolinacano** [comment]
I've tested the PR of the part 4 thoroughly and thanks to the manual tests I've fixed to bugs (https://github.com/doofinder/doofinder-woocommerce/commit/b89fdf0fc6efd0e95dd29bc1aec4eb23fa3715ea and https://github.com/doofinder/doofinder-woocommerce/commit/f398a4d0cc354143a51d7665003a5cd5f3071e45). After fixing them, every manual test has worked as expected, but I'm merging this after coming back from the holidays just in case.

**Comment by davidmolinacano** [comment]
We have adjusted the non-breaking parts to the WordPress and WooCommerce standards, but this is intended for now for internal use only. I mean, although more than 70-80% of the reported issues must have been solved, there is still room for improvement since we have omitted for now the most difficult parts to adapt. According to @sofia-doofinder and @IgnacioPursalsZ , we will postpone this task until Q4 and at that moment we'll solve the remaining errors, which are expected to be the most difficult ones to solve.

**Comment by IgnacioPursalsZ** [comment]
Aprovecho la oportunidad para mencionaros, @sofia-doofinder y @davidmolinacano , que esta tarea se ha quedado "en el aire". Por lo que probablemente tampoco se vaya a abordar en Q4, en cuanto tenga más noticias os informaré. Muchas gracias!

**Comment by davidmolinacano** [comment]
I'm going to move it again to BACKLOG until the Product team (@IgnacioPursalsZ) is interested on this issue again :smile: However, I think with the new modifications it should pass WooCommerce validation without any issue, so it can be also consider as DONE :raised_hands:

**Comment by davidmolinacano** [comment]
After talking with @sofia-doofinder we will close it for now and if we detect that there is anything remaining we will open it again.
